server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swico_db
    username: postgres   # 👈 Đảm bảo dùng 'postgres' thay vì 'admin'
    password: 123456     # 👈 Mật khẩu đúng bạn vừa dùng đăng nhập pgAdmin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: swico-secret-key-swico-secret-key-123456
    expiration-ms: 86400000